version: "3.1"
services:
  ms-email-consumer:
    build:
      context: ../..
      dockerfile: configs/ms-email-consumer/Dockerfile
    networks:
      confluent-ecosystem:
        aliases:
          - ms-email-consumer

networks:
  confluent-ecosystem:
    external: true
