server:
  port: 8080


spring:
  kafka:
    consumer:
      group-id: email-consumer
      max-poll-records: 3
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      specific.avro.reader: true
      schema.registry.url: http://schema-registry:8081
      bootstrap.servers: broker:29092

  application:
    name: ms-email-consumer
  main:
    banner-mode: off

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /actuator
      exposure:
        include: "*"


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%thread] %cyan(%logger{15}) : %msg%n"
  level:
    root: ERROR
    org.springframework.web: INFO
    com.intellias: DEBUG
    org.hibernate: ERROR
